import OpenAI from 'openai';
import { IImageService } from '../types';

/**
 * Service for generating AI-powered images using DALL-E API
 */
export class ImageService implements IImageService {
  private openai: OpenAI;

  constructor(apiKey: string) {
    if (!apiKey) {
      throw new Error('OpenAI API key is required');
    }

    this.openai = new OpenAI({ apiKey });
  }

  /**
   * Generate a festive Christmas image based on giftee description
   */
  async generateImage(gifteeDescription: string): Promise<Buffer> {
    const prompt = this.createPrompt(gifteeDescription);

    try {
      const response = await this.openai.images.generate({
        model: 'dall-e-3',
        prompt,
        n: 1,
        size: '1024x1024',
        quality: 'standard',
        response_format: 'url',
      });

      const imageUrl = response.data?.[0]?.url;
      if (!imageUrl) {
        throw new Error('No image URL generated by DALL-E');
      }

      // Download the image
      const imageBuffer = await this.downloadImage(imageUrl);
      return imageBuffer;
    } catch (error) {
      if (error instanceof Error) {
        throw new Error(`Failed to generate image: ${error.message}`);
      }
      throw new Error('Failed to generate image: Unknown error');
    }
  }

  /**
   * Create the prompt for DALL-E
   */
  private createPrompt(gifteeDescription: string): string {
    return `A festive Christmas illustration for Secret Santa gift exchange featuring elements related to: ${gifteeDescription}. Warm colors, cozy atmosphere, holiday theme, Christmas decorations. Artistic and cheerful style.`;
  }

  /**
   * Download image from URL and return as Buffer
   */
  private async downloadImage(url: string): Promise<Buffer> {
    try {
      const response = await fetch(url);
      if (!response.ok) {
        throw new Error(`Failed to download image: ${response.statusText}`);
      }

      const arrayBuffer = await response.arrayBuffer();
      return Buffer.from(arrayBuffer);
    } catch (error) {
      if (error instanceof Error) {
        throw new Error(`Failed to download image: ${error.message}`);
      }
      throw new Error('Failed to download image: Unknown error');
    }
  }

  /**
   * Add delay to avoid rate limiting
   */
  async delay(ms: number): Promise<void> {
    return new Promise(resolve => setTimeout(resolve, ms));
  }
}
