import OpenAI from 'openai';
import { ILlmService } from '../types';

/**
 * Service for generating AI-powered messages using OpenAI API
 */
export class LlmService implements ILlmService {
  private openai: OpenAI;
  private model: string = 'gpt-5-chat-latest';

  constructor(apiKey: string) {
    if (!apiKey) {
      throw new Error('OpenAI API key is required');
    }

    this.openai = new OpenAI({ apiKey });
  }

  /**
   * Generate a personalized Secret Santa message
   * @param gifterName Name of the person who will give the gift (recipient of this message)
   * @param gifteeName Name of the person who will receive the gift
   * @param gifteeDescription Description/interests of the gift receiver
   */
  async generateMessage(
    gifterName: string,
    gifteeName: string,
    gifteeDescription: string
  ): Promise<string> {
    const prompt = this.createPrompt(gifterName, gifteeName, gifteeDescription);

    try {
      const response = await this.openai.chat.completions.create({
        model: this.model,
        messages: [
          {
            role: 'system',
            content: 'Jesteś pomocnym asystentem, który pisze ciepłe, świąteczne wiadomości Secret Santa po polsku. Nie używaj formatowania markdown, takiego jak **pogrubienie**, *kursywa* lub inne znaki specjalne w celu podkreślenia. Używaj wyłącznie zwykłego tekstu.',
          },
          {
            role: 'user',
            content: prompt,
          },
        ],
      });

      const message = response.choices[0]?.message?.content?.trim();
      if (!message) {
        throw new Error('No message generated by OpenAI');
      }

      return message;
    } catch (error) {
      if (error instanceof Error) {
        throw new Error(`Failed to generate message: ${error.message}`);
      }
      throw new Error('Failed to generate message: Unknown error');
    }
  }

  /**
   * Create the prompt for OpenAI
   */
  private createPrompt(gifterName: string, gifteeName: string, gifteeDescription: string): string {
    return `Napisz krótką, ciepłą wiadomość Secret Santa dla ${gifterName}, który wylosował ${gifteeName}.

Wiadomość powinna:
- Poinformować ${gifterName}, że został Secret Santa dla ${gifteeName}
- Zawierać elementy wprowadzające w klimat świąt Bożego Narodzenia
- Dodaj jakieś zabawne lub urocze odniesienie do opisu wylosowanej osoby
- Zasugerować kreatywny pomysł na prezent bazując na zainteresowaniach: ${gifteeDescription}

Ton: przyjazny, świąteczny, entuzjastyczny. Pisz w sposób naturalny i osobisty.`;
  }

  /**
   * Add delay to avoid rate limiting
   */
  async delay(ms: number): Promise<void> {
    return new Promise(resolve => setTimeout(resolve, ms));
  }
}
